# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: connect228
# serverless.yml

service: connect-pharma-whatsapp

#custom: # add these two lines
 # secrets: ${file(secrets.json)} # reference the secrets.json file

provider:
  name: aws
  runtime: nodejs18.x
  #stage: dev
  region: eu-west-3
  #environment: # add environment property
    #NODE_ENV: ${self:custom.secrets.NODE_ENV} 
    # reference the NODE_ENV from the secrets.json file

functions:
  app:
    handler: dist/app.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true