-- https://supabase.com/docs/guides/database/extensions/postgis?queryGroups=language&language=result&queryGroups=database-method&database-method=sql

-- Create a dedicated separate schema
create schema if not exists "gis";

-- Example: enable the "postgis" extension
create extension postgis with schema "gis";

-- Example: disable the "postgis" extension
-- drop extension if exists postgis;



create table if not exists connect228_schema.restaurants (
	id int generated by default as identity primary key,
	name text not null,
	location gis.geography(POINT) not null
);

insert into connect228_schema.restaurants
  (name, location)
values
  ('Supa Burger', gis.st_point(-73.946823, 40.807416)),
  ('Supa Pizza', gis.st_point(-73.94581, 40.807475)),
  ('Supa Taco', gis.st_point(-73.945826, 40.80629));


create or replace function nearby_restaurants(lat float, long float)
returns table (id connect228_schema.restaurants.id%TYPE, name public.restaurants.name%TYPE, lat float, long float, dist_meters float)
set search_path = ''
language sql
as $$
  select id, name, gis.st_y(location::gis.geometry) as lat, gis.st_x(location::gis.geometry) as long, gis.st_distance(location, gis.st_point(long, lat)::gis.geography) as dist_meters
  from connect228_schema.restaurants
  order by location operator(gis.<->) gis.st_point(long, lat)::gis.geography;
$$;


-- grant usage on schema gis to root, authenticated;
grant usage on schema gis to root

SELECT nearby_restaurants(40.807313, -73.946713);
